# Generated by Django 3.1 on 2020-12-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_cours_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='institute',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='niveau',
            field=models.CharField(choices=[('1-primaire', '1_pri'), ('2-primaire', '2_pri'), ('3-primaire', '3_pri'), ('4-primaire', '4_pri'), ('5-primaire', '5_pri'), ('1-moyenne', '1_moy'), ('2-moyenne', '2_moy'), ('3-moyenne', '3_moy'), ('4-moyenne', '4_moy'), ('1-secondaire', '1_sec'), ('2-secondaire', '2_sec'), ('3-secondaire', '3_sec')], default='1-primaire', max_length=100),
        ),
    ]
