# Generated by Django 3.1 on 2021-03-09 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20210205_1929'),
        ('school', '0006_student_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('birthdate', models.DateField()),
                ('niveau', models.CharField(choices=[('N/A', 'N/A'), ('1-primaire', '1_pri'), ('2-primaire', '2_pri'), ('3-primaire', '3_pri'), ('4-primaire', '4_pri'), ('5-primaire', '5_pri'), ('1-moyenne', '1_moy'), ('2-moyenne', '2_moy'), ('3-moyenne', '3_moy'), ('4-moyenne', '4_moy'), ('1-secondaire', '1_sec'), ('2-secondaire', '2_sec'), ('3-secondaire', '3_sec')], default='1-primaire', max_length=100)),
                ('telephone', models.IntegerField()),
                ('cours_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
