# Generated by Django 3.1 on 2021-03-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20210312_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('photo', models.ImageField(default='Event-Default.png', upload_to='events_pics')),
            ],
        ),
    ]
