# Generated by Django 3.1 on 2021-03-24 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20210318_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=300)),
            ],
        ),
    ]
