# Generated by Django 3.1 on 2021-03-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_cmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmessage',
            name='content',
            field=models.CharField(max_length=300, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='cmessage',
            name='writer',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
