# Generated by Django 3.1 on 2021-03-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20210330_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmessage',
            name='read',
            field=models.BooleanField(default=True),
        ),
    ]
