# Generated by Django 3.1 on 2021-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_cmessage_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
