# Generated by Django 3.1 on 2021-01-28 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cours_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
