# Generated by Django 3.1 on 2021-01-28 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210128_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cours_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
