# Generated by Django 3.1 on 2020-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prof',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
