# Generated by Django 3.1 on 2020-12-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='wday',
            new_name='wday1',
        ),
        migrations.AddField(
            model_name='course',
            name='wday2',
            field=models.CharField(choices=[('Dimanche', 'Dim'), ('Lundi', 'Lun'), ('Mardi', 'Mar'), ('Mercredi', 'Mer'), ('Jeudi', 'Jeu'), ('Vendredi', 'Ven'), ('Samedi', 'Sam')], default='Dimanche', max_length=10),
        ),
    ]
