# Generated by Django 3.1 on 2020-12-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201220_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='wday1',
            field=models.CharField(choices=[('Dimanche', 'Dim'), ('Lundi', 'Lun'), ('Mardi', 'Mar'), ('Mercredi', 'Mer'), ('Jeudi', 'Jeu'), ('Vendredi', 'Ven'), ('Samedi', 'Sam')], default='---', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='wday2',
            field=models.CharField(choices=[('Dimanche', 'Dim'), ('Lundi', 'Lun'), ('Mardi', 'Mar'), ('Mercredi', 'Mer'), ('Jeudi', 'Jeu'), ('Vendredi', 'Ven'), ('Samedi', 'Sam')], default='---', max_length=10),
        ),
    ]
