# Generated by Django 3.1.4 on 2020-12-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeperiod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('N/A', 'N/A'), ('Dimanche', 'Dim'), ('Lundi', 'Lun'), ('Mardi', 'Mar'), ('Mercredi', 'Mer'), ('Jeudi', 'Jeu'), ('Vendredi', 'Ven'), ('Samedi', 'Sam')], default='N/A', max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
    ]
