# Generated by Django 3.1.4 on 2020-12-30 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_timeperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time2',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
