# Generated by Django 3.1 on 2021-02-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_cours_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='wday1',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Sunday', 'Dim'), ('Monday', 'Lun'), ('Tuesday', 'Mar'), ('Wednesday', 'Mer'), ('Thursday', 'Jeu'), ('Friday', 'Ven'), ('Saturday', 'Sam')], default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='wday2',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Sunday', 'Dim'), ('Monday', 'Lun'), ('Tuesday', 'Mar'), ('Wednesday', 'Mer'), ('Thursday', 'Jeu'), ('Friday', 'Ven'), ('Saturday', 'Sam')], default='N/A', max_length=10),
        ),
    ]
